name = "zpaynow-playground-server"
main = "index.js"
compatibility_date = "2024-03-20"

[vars]
APIKEY = "your-apikey"
SERVICE = "https://api.zpaynow.com"

[assets]
directory = "."
binding = "ASSETS"

